export default [
    {
        id:1,
        image:"redberryImg.png",
        label:"redberry blogs",
        link:"https://redberry-blogs.netlify.app/",
        description:"I developed an API-based project allowing users to log in and seamlessly create diverse blogs complete with images. This project significantly bolstered my expertise in API integration and proficient communication with backend systems.",
    },
    {
        id:2,
        image:"ioane-tech-hurryup.PNG",
        label:"Hurry up",
        link:"https://ioane-tech-hurryup.netlify.app",
        description:"Crafted fully functional game where players create teams and challenge opposing groups to guess word explanations. With a focus on functionality, the game offers an engaging experience centered on teamwork and word-solving excitement",
    },
    {
        id:3,
        image:"terminalImg.PNG",
        label:"Terminal",
        link:"https://ioane-tech-terminal.netlify.app",
        description:"Welcome to TerminalWebsite, where simplicity meets functionality! My website offers a unique and minimalist user interface reminiscent of a classic terminal environment, providing a nostalgic yet efficient browsing experience.",
    },
    {
        id:4,
        image:"b-work.PNG",
        label:"Business website",
        link:"https://b-work.netlify.app/",
        description:"Designed and developed a business-oriented website showcasing the diverse capabilities of the company. Leveraging various React libraries including typed, countUp, and react-intersection-observer, the website offers an interactive and dynamic user experience. Continuously learning and implementing new technologies, I strive to enhance the website's functionality and aesthetics.",
    },
    {
        id:5,
        image:"./shoppingImage.PNG",
        label:"Shopping service",
        link:"https://shopping-service.netlify.app/",
        description:"Online shopping website. feel free to explore its features.",
    },
    {
        id:6,
        image:"caffe-marr-io.PNG",
        label:"caffer marr-io",
        link:"https://ioane-tech-caffe-marr-io.netlify.app/",
        description:"Successfully completed the development of a cafe-restaurant website, meticulously fine-tuning its functionalities. Specializing in React's useContext feature, I ensured a seamless user experience for ordering food and efficient order tracking. This accomplishment underscores my dedication to delivering practical solutions that enhance customer satisfaction and operational efficiency.",
    },
    {
        id:7,
        image:"TbcImg.png",
        label:"TBC x Usaid ",
        link:"https://tbcxusaid-project.netlify.app/",
        description:"TBC React course project. TbsXusaid page clone. nothing much but a little bit of styling and functionality. practiced in responsiveness.",
    },
    {
        id:7,
        image:"ioane-tech-Weather.PNG",
        label:"Weather App",
        link:"https://ioane-tech-weather.netlify.app",
        description:"as",
    },
    {
        id:8,
        image:"ioane-tech-todolist.PNG",
        label:"To Do List",
        link:"https://ioane-tech-todolist.netlify.app/",
        description:"as",
    },   
    
]
